import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import { createApp } from "../src/app";
import { prisma } from "../src/lib/prisma";
import { processNotifications, cleanupHistory } from "../src/lib/notifications";
import { MailError } from "../src/lib/mailTransport";

async function main() {
  assert.equal(process.env.DATABASE_URL, "postgresql://review@127.0.0.1:5433/personal_review_tests", "Refuse to run against any other database");
  await prisma.$transaction([prisma.interaction.deleteMany(), prisma.pageView.deleteMany(), prisma.notificationJob.deleteMany(), prisma.comment.deleteMany(), prisma.article.deleteMany(), prisma.subscriber.deleteMany(), prisma.admin.deleteMany()]);
  await writeFile(process.env.MAIL_CAPTURE_PATH!, "");
  await prisma.admin.create({ data: { email: "admin@example.com", password: await bcrypt.hash("LocalTestPassword!", 10) } });
  const article = await prisma.article.create({ data: { title: "Test article", slug: "test-article", excerpt: "O'Connor's article", content: "Before\n\nAfter", published: true } });
  const draft = await prisma.article.create({ data: { title: "Private", slug: "private", excerpt: "Secret", content: "Private body", published: false } });
  const server = createApp().listen(0, "127.0.0.1");
  await new Promise<void>((resolve) => server.once("listening", resolve));
  const port = (server.address() as { port: number }).port;
  const base = `http://127.0.0.1:${port}/api`;
  const headers = { Origin: "http://127.0.0.1:5174", "X-Requested-With": "PersonalWebsite", "Content-Type": "application/json" };
  let cookie = "";
  let checks = 0;
  const check = (name: string) => { checks++; console.log(`PASS ${name}`); };
  const request = (path: string, method = "GET", body?: unknown, admin = false, extra = {}) => fetch(base + path, { method, headers: { ...headers, ...(admin ? { Cookie: cookie } : {}), ...extra }, body: body === undefined ? undefined : JSON.stringify(body) });
  try {
    const login = await request("/auth/login", "POST", { email: "admin@example.com", password: "LocalTestPassword!" });
    assert.equal(login.status, 200); cookie = login.headers.get("set-cookie")!.split(";")[0];
    assert.match(login.headers.get("set-cookie")!, /HttpOnly/); assert.equal(login.headers.get("x-content-type-options"), "nosniff"); check("login and security headers");
    process.env.NODE_ENV = "production";
    const localFrontend = process.env.FRONTEND_URL;
    process.env.FRONTEND_URL = "https://letterofforgiveness.com";
    const production = await request("/auth/login", "POST", { email: "admin@example.com", password: "LocalTestPassword!" }, false, { Origin: "https://letterofforgiveness.com" });
    assert.equal(production.status, 200);
    assert.match(production.headers.get("set-cookie")!, /Secure/); assert.match(production.headers.get("set-cookie")!, /SameSite=None/);
    const preflight = await request("/auth/login", "OPTIONS", undefined, false, { Origin: "https://letterofforgiveness.com", "Access-Control-Request-Method": "POST", "Access-Control-Request-Headers": "content-type,x-requested-with" });
    assert.equal(preflight.headers.get("access-control-allow-origin"), "https://letterofforgiveness.com");
    assert.match(preflight.headers.get("access-control-allow-headers")!, /X-Requested-With/);
    assert.equal((await request("/subscribers", "POST", { email: "local@example.com" })).status, 403);
    process.env.NODE_ENV = "development";
    process.env.FRONTEND_URL = localFrontend;
    check("production cookie flags, exact CORS preflight, and local-origin exclusion");
    assert.equal((await request("/articles/private")).status, 404);
    assert.equal((await request(`/comments/${draft.id}`)).status, 404);
    assert.equal((await request("/articles/private", "GET", undefined, true)).status, 200);
    const publicList = await (await request("/articles?admin=true")).json() as any;
    assert.equal(publicList.total, 1); check("draft bodies, comments, and lists require authentication");
    for (const route of ["summary", "activity", "subscribers", "notifications"]) assert.equal((await request(`/analytics/${route}`)).status, 401);
    const forged = jwt.sign({ id: "bad", email: "bad@example.com" }, process.env.JWT_SECRET!, { expiresIn: "1h" });
    assert.equal((await request("/auth/me", "GET", undefined, false, { Cookie: `token=${forged}` })).status, 401); check("analytics access and JWT shape validation");
    assert.equal((await request("/subscribers", "POST", { email: "csrf@example.com" }, false, { Origin: "https://attacker.vercel.app" })).status, 403);
    assert.equal((await request("/subscribers", "POST", { email: "csrf@example.com" }, false, { "X-Requested-With": "" })).status, 403);
    assert.equal((await request("/articles/1", "PUT", { title: "x" }, true, { Origin: "https://evil.example" })).status, 403);
    const cors = await request("/auth/me", "OPTIONS", undefined, false, { Origin: "https://attacker.vercel.app", "Access-Control-Request-Method": "POST" });
    assert.equal(cors.headers.get("access-control-allow-origin"), null); check("cross-origin and missing-header CSRF rejection");
    assert.equal((await request("/subscribers", "POST", { email: { $ne: null } })).status, 400);
    assert.equal((await request("/contact", "POST", { name: [], email: "bad", message: {} })).status, 400);
    assert.equal((await request(`/comments/${article.id}garbage`, "POST", { name: "Reader", body: "hello" })).status, 400);
    const injected = await request("/auth/login", "POST", { email: "' OR 1=1 --", password: "anything" }); assert.equal(injected.status, 400);
    assert.equal((await request("/articles?page=1%20OR%201=1")).status, 400); check("malformed objects, IDs, pagination, and SQL-injection inputs rejected");
    const comment = await request(`/comments/${article.id}`, "POST", { name: "O'Connor", body: "SELECT * FROM Article; ' OR 1=1 -- is literal text." });
    assert.equal(comment.status, 201); assert.equal(await prisma.article.count(), 2); check("legitimate punctuation and SQL-looking prose are stored as data");
    const signupBody = { email: "  READER@example.com " };
    const signups = await Promise.all([request("/subscribers", "POST", signupBody), request("/subscribers", "POST", signupBody)]);
    assert.equal(signups[0].status, 200); assert.deepEqual(await signups[0].json(), await signups[1].json());
    assert.equal(await prisma.subscriber.count(), 1); assert.equal(await prisma.notificationJob.count(), 1);
    assert.equal(await prisma.interaction.count({ where: { kind: "subscription" } }), 1); check("concurrent signup creates one subscriber, alert, and interaction");
    let key = "";
    await processNotifications(async (_mail, id) => { key = id!; throw new MailError("rate_limit", true); });
    const pending = (await prisma.notificationJob.findFirst())!;
    assert.equal(pending.status, "pending"); assert.equal(await prisma.subscriber.count(), 1);
    let sent = 0;
    await Promise.all([processNotifications(async (mail, id) => { sent++; assert.equal(id, key); assert.equal(mail.to, "samaritanbrotherseth@gmail.com"); assert.match(mail.text, /reader@example.com/); return "receipt-1"; }, pending.nextAttemptAt),
      processNotifications(async () => { sent++; return "receipt-2"; }, pending.nextAttemptAt)]);
    assert.equal(sent, 1); assert.equal((await prisma.notificationJob.findFirst())!.status, "sent"); check("email failure preserves subscription; retry and concurrent workers deduplicate");
    const recovered = await prisma.notificationJob.create({ data: { subscriberEmail: "restart@example.com", signupAt: new Date(), status: "processing", leaseUntil: new Date(Date.now() - 1000), firstAttemptAt: new Date(Date.now() - 60_000) } });
    await processNotifications(async () => "recovered");
    assert.equal((await prisma.notificationJob.findUnique({ where: { id: recovered.id } }))!.status, "sent");
    const expired = await prisma.notificationJob.create({ data: { subscriberEmail: "expired@example.com", signupAt: new Date(), firstAttemptAt: new Date(Date.now() - 24 * 60 * 60_000) } });
    await processNotifications(async () => { throw new Error("Must not send outside idempotency window"); });
    assert.equal((await prisma.notificationJob.findUnique({ where: { id: expired.id } }))!.lastError, "retry_window_expired"); check("worker restart recovery and 23-hour retry cutoff");
    const permanent = await prisma.notificationJob.create({ data: { subscriberEmail: "permanent@example.com", signupAt: new Date() } });
    await processNotifications(async () => { throw new MailError("invalid_sender", false); });
    assert.equal((await prisma.notificationJob.findUnique({ where: { id: permanent.id } }))!.status, "failed"); check("permanent provider failures are visible without endless retries");
    const capture = await prisma.notificationJob.create({ data: { subscriberEmail: "capture@example.com", signupAt: new Date() } });
    await processNotifications(); assert.equal((await prisma.notificationJob.findUnique({ where: { id: capture.id } }))!.status, "sent");
    const contact = await request("/contact", "POST", { name: "<img src=x onerror=alert(1)>", email: "contact@example.com", message: "<script>alert(1)</script> O'Connor" });
    assert.equal(contact.status, 200);
    const mails = (await readFile(process.env.MAIL_CAPTURE_PATH!, "utf8")).trim().split("\n").map((line) => JSON.parse(line));
    assert.equal(mails[0].to, "samaritanbrotherseth@gmail.com");
    assert.match(mails[1].html, /&lt;script&gt;/); assert.doesNotMatch(mails[1].html, /<script|<img/); check("captured signup alert and escaped contact email");
    const pausedAlert = await prisma.notificationJob.create({ data: { subscriberEmail: "paused@example.com", signupAt: new Date() } });
    process.env.MAIL_MODE = "disabled";
    await processNotifications();
    const pausedJob = (await prisma.notificationJob.findUnique({ where: { id: pausedAlert.id } }))!;
    assert.equal(pausedJob.status, "pending"); assert.equal(pausedJob.attempts, 0); assert.equal(pausedJob.firstAttemptAt, null);
    const pausedStatus = await (await request("/analytics/notifications", "GET", undefined, true)).json() as any;
    assert.equal(pausedStatus.deliveryEnabled, false);
    assert.equal((await request("/contact", "POST", { name: "Reader", email: "reader@example.com", message: "Hello" })).status, 503);
    assert.equal((await readFile(process.env.MAIL_CAPTURE_PATH!, "utf8")).trim().split("\n").length, 2);
    process.env.MAIL_MODE = "capture";
    await processNotifications();
    assert.equal((await prisma.notificationJob.findUnique({ where: { id: pausedAlert.id } }))!.status, "sent");
    check("disabled delivery preserves unattempted alerts, reports status, and refuses undelivered contact messages");
    const view = { id: randomUUID(), path: `/articles/${article.slug}`, referrerHost: "google.com", device: "mobile" };
    await request("/analytics/pageviews", "POST", view); await request("/analytics/pageviews", "POST", view);
    assert.equal(await prisma.pageView.count(), 1);
    await request("/analytics/pageviews", "POST", { ...view, id: randomUUID() }, false, { DNT: "1" });
    await request("/analytics/pageviews", "POST", { ...view, id: randomUUID() }, false, { "Sec-GPC": "1" });
    assert.equal(await prisma.pageView.count(), 1);
    for (const path of ["/admin/dashboard", "/articles/private", "/?token=secret", "/not-found"]) assert.equal((await request("/analytics/pageviews", "POST", { ...view, id: randomUUID(), path })).status, 400);
    assert.equal((await request("/analytics/pageviews", "POST", { ...view, id: randomUUID(), referrerHost: "https://google.com/secret?q=email" })).status, 400); check("page views deduplicate, exclude private/unknown pages, and honor DNT/GPC");
    const summary = await (await request("/analytics/summary?days=7", "GET", undefined, true)).json() as any;
    assert.deepEqual(summary.totals, { views: 1, subscriptions: 1, comments: 1, contacts: 1 });
    assert.equal(summary.daily.length, 7); assert.equal(summary.sources[0].source, "google.com"); assert.equal(summary.devices[0].device, "mobile");
    const activity = await (await request("/analytics/activity", "GET", undefined, true)).json() as any;
    assert.equal(activity.total, 3); assert.equal(activity.items.some((i: any) => i.email === "contact@example.com"), true);
    const subs = await (await request("/analytics/subscribers", "GET", undefined, true)).json() as any;
    assert.equal(subs.items[0].unsubscribeToken, undefined); check("analytics totals, daily chart, sources, devices, and private identity responses");
    const old = new Date(Date.now() - 91 * 24 * 60 * 60_000);
    await prisma.pageView.create({ data: { ...view, id: randomUUID(), day: old, createdAt: old } });
    await prisma.interaction.create({ data: { kind: "contact", sourceId: "old", email: "old@example.com", createdAt: old } });
    await prisma.notificationJob.create({ data: { subscriberEmail: "old@example.com", signupAt: old, createdAt: old } });
    await processNotifications(async () => { throw new Error("Must not send an alert outside 90-day retention"); });
    assert.equal((await prisma.notificationJob.findFirst({ where: { subscriberEmail: "old@example.com" } }))!.attempts, 0);
    await cleanupHistory(); assert.equal(await prisma.pageView.count(), 1); assert.equal(await prisma.interaction.count(), 3);
    assert.equal(await prisma.notificationJob.count({ where: { subscriberEmail: "old@example.com" } }), 0);
    assert.equal(await prisma.subscriber.count(), 1); assert.equal(await prisma.comment.count(), 1); check("90-day retention removes history while preserving subscriptions and comments");
    const large = { title: "Image test", slug: "image-test", excerpt: "Test", content: "Before\n\n![](data:image/png;base64," + "YQ==".repeat(50_000) + ")\n\nAfter", published: false };
    const saved = await request("/articles", "POST", large, true); assert.equal(saved.status, 201);
    const savedArticle = await saved.json() as any;
    const reopened = await (await request(`/articles/${savedArticle.id}`, "GET", undefined, true)).json() as any;
    assert.equal(reopened.content, large.content); check("image articles above the former 100 KB limit save/reopen without reordering");
    assert.equal((await request("/articles", "POST", large)).status, 401);
    assert.equal((await request("/articles", "POST", { ...large, slug: "123" }, true)).status, 400); check("large writes authenticate before parsing; numeric-only slug collisions prevented");
    for (const [url, provider] of [["https://www.youtube.com/watch?v=dQw4w9WgXcQ", "YouTube"], ["https://vimeo.com/123456789", "Vimeo"], ["https://open.spotify.com/track/abc123", "Spotify"]]) {
      const embed = await request(`/embed?url=${encodeURIComponent(url)}`);
      assert.equal(embed.status, 200); assert.equal((await embed.json() as any).provider, provider);
    }
    check("existing YouTube, Vimeo, and Spotify provider embeds remain available");
    assert.equal((await request("/articles", "POST", { ...large, slug: "oversized", content: "x".repeat(8 * 1024 * 1024) }, true)).status, 413);
    assert.equal((await request("/contact", "POST", { name: "name", email: "a@b.com", message: "x".repeat(20_000) })).status, 413); check("article and public-form request size limits");
    let rate = 200;
    for (let i = 0; i < 12; i++) rate = (await request("/auth/login", "POST", { email: "none@example.com", password: "wrong" })).status;
    assert.equal(rate, 429); check("login throttling");
    const sub = (await prisma.subscriber.findFirst())!;
    assert.equal((await request(`/subscribers/unsubscribe/${sub.unsubscribeToken}`)).status, 200);
    assert.equal(await prisma.subscriber.count(), 0); assert.equal((await prisma.interaction.findFirst({ where: { kind: "subscription" } }))!.email, null); check("unsubscribe removes active identity from analytics history");
    console.log(`${checks} integration scenarios passed against isolated PostgreSQL.`);
  } finally { await new Promise<void>((resolve) => server.close(() => resolve())); await prisma.$disconnect(); }
}
main().catch((err) => { console.error(err); process.exitCode = 1; });
